### ISSUE TITLE
cannot build on ubuntu 12.04

### ISSUE THREAD

**Issue by chchgb** [lscube/feng#1]
CC     src/media/feng-parser_mpegaudio.o
  CC     src/media/feng-resource_avformat.o
src/media/resource_avformat.c: In function ‘avf_open’:
src/media/resource_avformat.c:146:14: error: ‘AV_CODEC_ID_MPEG1VIDEO’ undeclared (first use in this function)
src/media/resource_avformat.c:146:14: note: each undeclared identifier is reported only once for each function it appears in
src/media/resource_avformat.c:147:14: error: ‘AV_CODEC_ID_MPEG2VIDEO’ undeclared (first use in this function)
src/media/resource_avformat.c:153:14: error: ‘AV_CODEC_ID_H264’ undeclared (first use in this function)
src/media/resource_avformat.c:163:14: error: ‘AV_CODEC_ID_MP2’ undeclared (first use in this function)
src/media/resource_avformat.c:164:14: error: ‘AV_CODEC_ID_MP3’ undeclared (first use in this function)
src/media/resource_avformat.c:170:14: error: ‘AV_CODEC_ID_VORBIS’ undeclared (first use in this function)
src/media/resource_avformat.c:180:14: error: ‘AV_CODEC_ID_THEORA’ undeclared (first use in this function)
src/media/resource_avformat.c:190:14: error: ‘AV_CODEC_ID_SPEEX’ undeclared (first use in this function)
src/media/resource_avformat.c:195:14: error: ‘AV_CODEC_ID_AAC’ undeclared (first use in this function)
src/media/resource_avformat.c:226:14: error: ‘AV_CODEC_ID_MPEG4’ undeclared (first use in this function)
src/media/resource_avformat.c:236:14: error: ‘AV_CODEC_ID_H263’ undeclared (first use in this function)
src/media/resource_avformat.c:243:14: error: ‘AV_CODEC_ID_AMR_NB’ undeclared (first use in this function)
src/media/resource_avformat.c:251:14: error: ‘AV_CODEC_ID_VP8’ undeclared (first use in this function)
src/media/resource_avformat.c: In function ‘avf_read_packet’:
src/media/resource_avformat.c:407:14: error: ‘AV_CODEC_ID_MP2’ undeclared (first use in this function)
src/media/resource_avformat.c:408:14: error: ‘AV_CODEC_ID_MP3’ undeclared (first use in this function)
make[1]: **\* [src/media/feng-resource_avformat.o] Error 1
make[1]: Leaving directory `/home/ubuntu/Work/feng/feng-master'
make: **\* [all] Error 2
